USE [master]
GO

/****** Object:  Database [GEO_CRM]    Script Date: 08/04/2018 20:16:22 ******/
CREATE DATABASE [GEO_CRM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GEO_CRM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\GEO_CRM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GEO_CRM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\GEO_CRM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GEO_CRM] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GEO_CRM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GEO_CRM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GEO_CRM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GEO_CRM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GEO_CRM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GEO_CRM] SET ARITHABORT OFF 
GO

ALTER DATABASE [GEO_CRM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GEO_CRM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GEO_CRM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GEO_CRM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GEO_CRM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GEO_CRM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GEO_CRM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GEO_CRM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GEO_CRM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GEO_CRM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GEO_CRM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GEO_CRM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GEO_CRM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GEO_CRM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GEO_CRM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GEO_CRM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GEO_CRM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GEO_CRM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GEO_CRM] SET  MULTI_USER 
GO

ALTER DATABASE [GEO_CRM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GEO_CRM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GEO_CRM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GEO_CRM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GEO_CRM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GEO_CRM] SET QUERY_STORE = OFF
GO

USE [GEO_CRM]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GEO_CRM] SET  READ_WRITE 
GO


